### ISSUE TITLE
Project crashes while running

### ISSUE THREAD

**Issue by Kromster80** [Poznamenany/ExtAI_test_with_DLL#2]
1. Auto Fill
2. Init
3. Run
4. Crash:
![image](https://user-images.githubusercontent.com/4618474/52531847-a44b9480-2d24-11e9-9ad6-de4ec7e2eaf6.png)

Stack Trace:
:75161389 kernel32.GetConsoleMode + 0x61
:5d81cc35 ; C:\Windows\SysWOW64\DWRITE.DLL
:5d81bfa0 ; C:\Windows\SysWOW64\DWRITE.DLL
:5d81b4fe ; C:\Windows\SysWOW64\DWRITE.DLL
:5d81a951 ; C:\Windows\SysWOW64\DWRITE.DLL
:5d82d739 ; C:\Windows\SysWOW64\DWRITE.DLL
FMX.Canvas.D2D.TTextLayoutD2D.DoRenderLayout
FMX.TextLayout.TTextLayout.NeedUpdate
FMX.TextLayout.TTextLayout.SetText(???)
FMX.Objects.TText.SetText(???)
FMX.StdCtrls.TPresentedTextControl.UpdateTextObject($80FC8F0,'Start')
FMX.StdCtrls.TPresentedTextControl.DoChanged
FMX.StdCtrls.TPresentedTextControl.Change
FMX.StdCtrls.TPresentedTextControl.SetText(???)
TestDLLWin.TPPLWin.RefreshSimButtons(nil)

**Comment by Kromster80** [comment]
Doesn't happen now (could be fixed by some of my commits?)

**Comment by Poznamenany** [comment]
FMX.Canvas.D2D.TTextLayoutD2D.DoRenderLayout - problem was in refreshing simulation button every game tick (can be solved by conditions and event onSimulationStateChanged) - it happens in long simulations
