### ISSUE TITLE
Project crashes on exit

### ISSUE THREAD

**Issue by Kromster80** [Poznamenany/ExtAI_test_with_DLL#3]
1. Auto Fill
2. Init
3. Close the form
4. Crash:
![image](https://user-images.githubusercontent.com/4618474/52531866-e4127c00-2d24-11e9-805c-dfb73c5ec5ae.png)

Call Stack:
ExtAIThread.TExtAIThread.Execute
System.Classes.ThreadProc($379B178)
System.ThreadWrapper($5441F40)
:751633aa kernel32.BaseThreadInitThunk + 0x12
:771d9ef2 ntdll.RtlInitializeExceptionChain + 0x63
:771d9ec5 ntdll.RtlInitializeExceptionChain + 0x36

**Comment by Poznamenany** [comment]
Simulation must be terminated onClose event not onDestroy => 
procedure TPPLWin.FormClose(Sender: TObject; var aAction: TCloseAction);
was used instead of TPPLWin.FormDestroy
